# Generated by Django 5.2.5 on 2025-09-19 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(error_messages={'blank': 'لطفاً نام را وارد کنید.', 'invalid_name': 'نام فقط باید شامل حروف فارسی باشد.', 'max_length': 'نام نمی\u200cتواند بیشتر از ۲۵۰ کاراکتر باشد.'}, help_text='حداکثر ۲۵۰ کاراکتر. فقط حروف فارسی مجاز است.', max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_name', message='این فیلد فقط می\u200cتواند شامل حروف فارسی یا عربی باشد.', regex='^[آ-یءئ\\s\u200cيك]+$')], verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(error_messages={'blank': 'لطفاً نام خانوادگی را وارد کنید.', 'invalid_name': 'نام خانوادگی فقط باید شامل حروف فارسی باشد.', 'max_length': 'نام خانوادگی نمی\u200cتواند بیشتر از ۲۵۰ کاراکتر باشد.'}, help_text='حداکثر ۲۵۰ کاراکتر. فقط حروف فارسی مجاز است.', max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_name', message='این فیلد فقط می\u200cتواند شامل حروف فارسی یا عربی باشد.', regex='^[آ-یءئ\\s\u200cيك]+$')], verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(error_messages={'unique': 'این شماره تلفن قبلاً استفاده شده است.'}, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='شماره تلفن باید با 09 شروع شده و 11 رقم باشد.', regex='^09\\d{9}$')], verbose_name='شماره تلفن'),
        ),
    ]
