# Generated by Django 5.2.5 on 2025-09-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_appointment_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.CharField(blank=True, choices=[('8_00', '08:00'), ('8_30', '08:30'), ('9_00', '09:00'), ('9_30', '09:30'), ('10_00', '10:00'), ('10_30', '10:30')], max_length=6, null=True),
        ),
    ]
