# Generated by Django 5.2.4 on 2025-08-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserve',
            options={'ordering': ('-created_at',), 'verbose_name': 'رزرو', 'verbose_name_plural': 'رزروها'},
        ),
        migrations.AlterField(
            model_name='reserve',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ اپدیت'),
        ),
    ]
